### ISSUE TITLE
Getting new tokens at every page

### ISSUE THREAD

**Issue by lferran** [plone/guillotina_gcloudstorage#2]
When iterating a bucket, we are getting a new token at every page, regardless of whether it was expired:
https://github.com/guillotinaweb/guillotina_gcloudstorage/blob/master/guillotina_gcloudstorage/storage.py#L110

Plus, I don't see why we should run `self._get_access_token()` in an executor ([see here](https://github.com/guillotinaweb/guillotina_gcloudstorage/blob/master/guillotina_gcloudstorage/storage.py#L337)), if `googleapis/oauth2client.service_account.ServiceAccountCredentials` is not waiting for network or disk:

https://github.com/googleapis/oauth2client/blob/0d1c814779c21503307b2f255dabcf24b2a107ac/oauth2client/service_account.py#L602

**Comment by lferran** [comment]
oh, I see that `oauth2client` takes care of returning a new token only if the current one has expired :+1: 

https://github.com/googleapis/oauth2client/blob/0d1c814779c21503307b2f255dabcf24b2a107ac/oauth2client/service_account.py#L613

@vangheem any reason why running it an executor?

**Comment by vangheem** [comment]
Only reason I imagine is because it was assumed it could perform an http request. If it doesn't, then it can be removed.

**Comment by lferran** [comment]
:+1: I'll prepare the PR then. thanks!
