### ISSUE TITLE
Backport bugfix to 1.x

### ISSUE THREAD

**Issue by lferran** [plone/guillotina_gcloudstorage#4]
@vangheem would it be possible to backport [this commit](guillotinaweb/guillotina_gcloudstorage@6f3f0d5#diff-789604b13fddb96d9dec12a45ed3fd9a) to version 1.1.7 and have it as a new 1.1.8 release?

I'd do it, but I'm not sure what's the standard procedure you use in this case

**Comment by vangheem** [comment]
@lferran of course! I think easiest would be for you to make a PR for the changes against the 1.x branch. I'll merge and then make a release.

**Comment by vangheem** [comment]
I just cut the 1.x branch which should be at the correct git commit spot: https://github.com/guillotinaweb/guillotina_gcloudstorage/tree/1.x

Please let me know if you have any issues!
